[theme]
  background = "#000000"
  marker_background = "#ad46ff"
  marker_insert_background = "#ad46ff"
  marker_replace_background = "#c27aff"
  index_marker_background = "#3c0366"
  legend_background = "#59168b"
  legend_highlight = "#c27aff"
  border_color = "#8200db"
  endian_color = "#3c0366"
  active_tab = "#9810fa"
  selection_background = "#ad46ff"
  unsaved_file_color = "#dab2ff"
  disabled_color = "#59168b"
  bit16_background = "#59168b"
  bit32_background = "#ad46ff"
  bit64_background = "#59168b"
  bit128_background = "#ad46ff"
